### PR TITLE
Fixing test, minor optimizations, ESLinting

### LINKED ISSUE #7: Local tests fails
- The file `package.browserify.js` is missing.
- Local test launch with `meteor test-packages ./ --port 3010` is not able to find the npm directory.

### PR DESCRIPTION
**Pull request by PEM--**
- Fix #7
- Avoid `else` when the `if` condition has a `return`
- Add a testing in the README
- Add a `.gitignore` in order to avoid importing npm
- Bump dependencies
- Bump release

### CODE REVIEW

File: package.js [hunk 1]
```diff
@@ -1,14 +1,24 @@
 Package.describe({
   name: 'kadira:dochead',
   summary: 'Isomorphic way to manipulate document.head for Meteor apps',
-  version: '1.1.0',
+  version: '1.1.1',
```
Comment (arunoda) [inline package.js:4]: Don't bump the release :)
